# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 70b7a2a04983bef1a71cab46dfd6172b13481d860e86331e73402d0964e100c28fcf29492b3b8630c46a9889c71fd07f7d5907401771613e173ca9f053571c17

test:
  secret_key_base: d3257f876e72813c9aa36ecc67713358e5db7100c64ae6c940a80f5ede85c56cd8c7d655b18adbd8c0a5962193eabf771a02b471ebf021cd7924d89945a19a93

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
